### ISSUE TITLE
tokenizer.pad_token_id is None

### ISSUE THREAD

**Issue by simplespeech** [cwang621/blsp#1]
The first training stage, tokenizer.pad_token_id is None. It seems need to add tokenizer.pad_token_id = (
        0  # unk. we want this to be different from the eos token
    )
after get the tokenizer.

**Comment by cwang621** [comment]
You are right.
The base model of llama does not have pad_token_id. We need to manually set it to 0 after getting the tokenizer.
We will fix this bug in train_stage1.py
